---
# |For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: My Home Page

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

theme: dark # or light

color: slate

language: en

target: _blank # Possible options include _blank, _self, and _top