services:
  drawio:
    image: jgraph/drawio:26.1.1
    container_name: drawio
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - 8095:8080
    # #   # - 8443:8443
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      PUBLIC_DNS: $DRAWIO_DNS
      ORGANISATION_UNIT: MyOrg
      ORGANISATION: MyOrg
      CITY: Orgland
      STATE: OrgState
      COUNTRY_CODE: USA
    labels:
      #Homepage
      # - homepage.group=Apps
      # - homepage.name=Draw.io
      # - homepage.icon=draw-io.png
      # - homepage.href=https://drawio.$DOMAINNAME_3
      # - homepage.description=Online Diagrams
      #Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.drawio-rtr.entrypoints=websecure"
      - "traefik.http.routers.drawio-rtr.rule=Host(`drawio.$DOMAINNAME_3`)"
      # Middlewares
      - "traefik.http.routers.drawio-rtr.middlewares=chain-authentik-proxy-auth@file"
      # HTTP Services
      - "traefik.http.routers.drawio-rtr.service=drawio-svc"
      - "traefik.http.services.drawio-svc.loadbalancer.server.port=8080"