services:
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  # https://github.com/linuxserver/docker-socket-proxy/
  # https://docs.docker.com/engine/api/
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:1.26.3
    container_name: socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - socket_proxy
    ports:
     - "127.0.0.1:2375:2375"
    environment:
      - ALLOW_START=0 #optional
      - ALLOW_STOP=0 #optional
      - ALLOW_RESTARTS=0 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 #Traefik, Homepage, Authentik
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=0 #optional
      - IMAGES=1 #Portainer, Authentik
      - INFO=1 #Portainer, Authentik
      # - NETWORKS=1 #Portainer
      - NETWORKS=0 #Portainer
      - NODES=0 #optional
      - PING=1 #optional
      - POST=1 #Watchtower, Homepage, Authentik
      - PLUGINS=0 #optional
      - SECRETS=0 #optional
      - SERVICES=1 #Portainer, Homepage
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=1 #Portainer, Homepage
      - VERSION=1 #optional
      # - VOLUMES=1 #Portainer
      - VOLUMES=0 #Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    read_only: true
    tmpfs:
      - /run

  # docker exec -it socket-proxy /bin/sh