Work in Progress

---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:1.0.0-1032

dependencies:
  galaxy:
    collections:
      - name: ansible.windows
        version: 3.1.0
      - name: community.windows
        version: 3.0.0
      - name: microsoft.iis
        version: 1.0.2
      - name: miscrosoft.sql
        version: 2.5.2
      - name: community.general
        version: 10.7.0
      - name: ansible.utils
        version: 6.0.0
      - name: ansible.posix
        version: 2.0.0
      - name: ansible.scm
        version: 3.0.0
      - name: ansible.netcommon
        version: 8.0.0
  python:
    - pyVmomi==8.0.3.0.1
    - winrm?
    - ssh?