---
- name: Create systemd service unit file
  template:
    src: ../external_scripts/dockerhealth-systemd-template.j2
    dest: /etc/systemd/system/docker-health-check.service
  notify: Reload systemd