services:
  #https://www.youtube.com/watch?v=tIazVdhsSqQ
  #Good examples beyond the simple basics
  uptimekuma:
    image: louislam/uptime-kuma:1.23.16-alpine
    container_name: uptimekuma
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $DOCKERDIR/uptimekuma/data:/app/data
    # ports:
    #  - 127.0.0.1:3567:3001
    labels:
      # - homepage.group=Infrastructure
      # - homepage.name=UptimeKuma
      # - homepage.icon=uptime-kuma.png
      # - homepage.href=https://uptime.$DOMAINNAME_1
      # - homepage.description=Network Monitoring Tool
      #Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.uptimekuma-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma-rtr.rule=Host(`uptime.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.uptimekuma-rtr.middlewares=chain-authentik-proxy-auth@file"
      # HTTP Services
      - "traefik.http.routers.uptimekuma-rtr.service=uptimekuma-svc"
      - "traefik.http.services.uptimekuma-svc.loadbalancer.server.port=3001"