services:
  # VSCode - VSCode Editing
  vscode: 
    image: lscr.io/linuxserver/code-server:4.98.2
    container_name: vscode
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - proxy
    # ports:
    #   - 8443:8443
    volumes:
      - $DOCKERDIR:/data/docker
      - $DOCKERDIR/code-server/config:/config
      # - $DATADIR1:/data/data #Define directory to be used by code server
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      # DOCKER_HOST: tcp://socket-proxy:2375
      # PASSWORD: $VSCODE_PASSWORD
      # HASHED_PASSWORD: #optional
      # SUDO_PASSWORD: password #optional
      # SUDO_PASSWORD_HASH: #optional
      # PROXY_DOMAIN: code-server.my.domain #optional
      # DEFAULT_WORKSPACE: /config/data/User/Workspaces/AZ.code-workspace #optional
    labels:
      #Homepage
      # - homepage.group=Apps
      # - homepage.name=Code Server
      # - homepage.icon=code-server.png
      # - homepage.href=https://code.$DOMAINNAME_1
      # - homepage.description=Web IDE
      #Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=websecure"
      - "traefik.http.routers.vscode-rtr.rule=Host(`code.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-authentik-proxy-auth@file"
      # HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"