---
#Install Tailscale
# - name: Install Tailscale
  - hosts: all
    vars_files: '../vault.yml'
    roles:
      - role: artis3n.tailscale
        vars:
          # Example pulling the API key from the env vars on the host running Ansible
          # tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
          tailscale_authkey: "{{ tailscale_key }}"
          tailscale_args: "--ssh"